version: '3.1'

services:

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: lobe
      POSTGRES_USER: lobe
      POSTGRES_DB: lobe
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./instance_folder_prod/pgdata:/var/lib/postgresql/data

  lobe:
    image: docker.greynir.is/lobe
    restart: always
    environment:
      - FLASK_INSTANCE_PATH=/instance_folder
    volumes:
      - ./instance_folder_prod:/instance_folder
    ports:
      - 5000:5000
